language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - sudo apt-get install libboost-dev
  - cargo build --verbose
  - cargo build --verbose --features serde_support
  - cargo build --verbose --features strict_encoding_support
  - cargo build --verbose --all-features
  - cargo test --verbose --all-features
