[package]
name = "monero"
description = "Rust Monero Library."
keywords = ["monero"]
version = "0.11.2"
authors = ["h4sh3d <h4sh3d@protonmail.com>"]
license = "MIT"
homepage = "https://github.com/monero-rs/monero-rs"
repository = "https://github.com/monero-rs/monero-rs"
documentation = "https://docs.rs/monero"
readme = "README.md"
include = [
    "src/*",
    "README.md",
    "LICENSE",
]

edition = "2018"

[features]
default = ["full"]
full = ["fixed-hash/std", "fixed-hash/rand", "rand/std"]
serde_support = ["serde", "serde-big-array"]
strict_encoding_support = ["strict_encoding"]

[dependencies]
hex = "0.4.3"
hex-literal = "0.3.1"
keccak-hash = "0.7.0"
base58-monero = { version = "0.3", default-features = false }
serde = { version = "1.0.124", features = ["derive"], optional = true }
serde-big-array = { version = "0.3.2", optional = true }
curve25519-dalek = { version = "3.0.2", features = ["serde"] }
thiserror = "1.0.24"
strict_encoding = { version = "1.2", optional = true }
subtle = { version = "2", default-features = false }
hash_edwards_to_edwards = { git = "https://github.com/comit-network/hash_edwards_to_edwards" }
integer-encoding = "3"
rand = { version = "0.7", optional = true }
lazy_static = "1"
clear_on_drop = { version = "0.2", default-features = false }

[dependencies.fixed-hash]
version = "0.7.0"
default-features = false

[dev-dependencies]
rand = { version = "0.7", features = ["std"] }
serde_json = "1"

[badges]
travis-ci = { repository = "monero-rs/monero-rs", branch = "master" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
